export const initialPlayers = [
  { name: '김태우', tier: 'silver', preferredPositions: ['top', 'adc', 'jungle'] },
  { name: '임대원', tier: 'diamond', preferredPositions: ['support', 'adc', 'jungle', 'top', 'mid'] },
  { name: '이상훈', tier: 'silver', preferredPositions: ['adc', 'top'] },
  { name: '김동현', tier: 'bronze', preferredPositions: ['top', 'support'] },
  { name: '황희승', tier: 'emerald', preferredPositions: ['mid', 'support', 'adc', 'jungle'] },
  { name: '이찬준', tier: 'gold', preferredPositions: ['jungle', 'mid', 'adc'] },
  { name: '정준영', tier: 'platinum', preferredPositions: ['jungle', 'top', 'support', 'adc', 'mid'] },
  { name: '강정훈', tier: 'bronze', preferredPositions: ['support', 'top', 'mid'] },
  { name: '구교준', tier: 'bronze', preferredPositions: ['top', 'mid', 'support', 'adc', 'jungle'] },
  { name: '김병호', tier: 'diamond', preferredPositions: ['jungle', 'top', 'adc'] },
  { name: '이규빈', tier: 'silver', preferredPositions: ['support', 'adc', 'top', 'jungle', 'mid'] },
  { name: '이종혁', tier: 'bronze', preferredPositions: ['jungle'] },
  { name: '박진현', tier: 'silver', preferredPositions: ['support', 'adc', 'top'] },
  { name: '스펜서', tier: 'silver', preferredPositions: ['top', 'mid', 'support', 'adc'] },
  { name: '구본근', tier: 'diamond', preferredPositions: ['top', 'jungle', 'mid', 'adc', 'support'] },
  { name: '권예창', tier: 'gold', preferredPositions: ['jungle', 'support'] },
  { name: '조관중', tier: 'bronze', preferredPositions: ['top', 'support', 'mid', 'jungle', 'adc'] },
  { name: '심재원', tier: 'emerald', preferredPositions: ['top'] },
  { name: '박성현', tier: 'diamond', preferredPositions: ['adc', 'mid'] },
  { name: '정의건', tier: 'bronze', preferredPositions: ['support', 'top'] },
  { name: '정한용', tier: 'master+', preferredPositions: ['jungle', 'adc', 'top', 'mid', 'support'] },
  { name: '이한슬', tier: 'master+', preferredPositions: ['mid', 'adc'] },
  { name: '정호원', tier: 'gold', preferredPositions: ['top', 'support', 'mid'] },
  { name: '김재현', tier: 'diamond', preferredPositions: ['mid', 'jungle', 'top'] },
  { name: '강민', tier: 'diamond', preferredPositions: ['support', 'adc', 'top', 'jungle', 'mid'] },
  { name: '추지웅', tier: 'bronze', preferredPositions: ['adc', 'mid', 'top', 'jungle', 'support'] },
  { name: '문호빈', tier: 'bronze', preferredPositions: ['support', 'jungle', 'top'] },
  { name: '윤수열', tier: 'iron', preferredPositions: ['support', 'top'] },
  { name: '최창헌', tier: 'bronze', preferredPositions: ['top', 'mid'] },
  { name: '이훈', tier: 'diamond', preferredPositions: ['top', 'jungle', 'mid'] },
]; 